# -*- coding: utf-8 -*-
"""sdw2023_versao_final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FQdpkVklbfGKdOz0nNjJomt09z62_Tsp
"""

!pip install openai

import pandas as pd
import openai

# Carrega o DataFrame
df = pd.read_csv('sdwdados2023.csv', delimiter=';', index_col=None)

# Define a chave da API OpenAI
openai_api_key = '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'
openai.api_key = openai_api_key

# Função para gerar mensagens personalizadas para cada usuário
def generate_ai_news(user):
    completion = openai.ChatCompletion.create(
        model="gpt-4",
        messages=[
            {
                "role": "system",
                "content": f"Crie uma mensagem para {user['name']} sobre a importância dos investimentos (máximo de 100 caracteres)"
            },
            {
                "role": "user",
                "content": f"Crie uma mensagem para {user['name']} sobre como é importante investir. (máximo de 100 caracteres)"
            }
        ]
    )
    return completion.choices[0].message['content'].strip('\"')

# Lista para armazenar mensagens personalizadas para cada usuário
mensagens_personalizadas = []

# Itera pelas linhas do DataFrame
for index, row in df.iterrows():
    news = generate_ai_news(row)
    mensagens_personalizadas.append(news)
    print(f"Mensagem para {row['name']}: {news}")

# Agora, a lista mensagens_personalizadas contém as mensagens geradas para cada usuário
print("Mensagens personalizadas para todos os usuários:")
for user, mensagem in zip(df['name'], mensagens_personalizadas):
    print(f"{user}: {mensagem}")